run:
  tests: false

  # issues:
  #   include:
  #     - EXC0001
  #     - EXC0005
  #     - EXC0011
  #     - EXC0012
  #     - EXC0013

  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  # enable-all: true
  enable:
    - bodyclose
    - dupl
    - exportloopref
    - goconst
    # - godot
    # - godox
    - goimports
    - goprintffuncname
    - gosec
    - misspell
    - prealloc
    # - revive
    - rowserrcheck
    - sqlclosecheck
    - unconvert
    - unparam
    - whitespace
    - errcheck
    - nilerr
    - nilnil
    - errname
    - wrapcheck

rules:
  - linters:
      - godox
    severity: warn
